apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  labels:
    app: playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: app
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  selector:
    app: playground
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 30100

# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: playground-ingress
#   namespace: dev
# spec:
#   ingressClassName: traefik
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: playground-service
#             port:
#               number: 80
